### ISSUE TITLE
Map of Event Commands

### ISSUE THREAD

**Issue by Ryex** [borisblizzard/arcreator#30]
I had a shower thought as to how to greatly simplify the management of the Event Editor.

Everything would just be so much simpler if I had a central map/structure of the event commands and their params for reference, at which point I could employ some meta programming and implement the formater, processor, properties panel etc. all in one class a piece instead of a new class for every single command.

The map should probably be made with JSON or YAML either one. the goal here is to map each command to a map of it's positional params and their types

for example in YAML command 132 "Change Battle BGM" would look like so in yaml
```yaml
# command #
132:
    # param position
    0:
        # type is AudioFile, specifically a BGM
        type: AudioFile_BGM
        # peram name for display 
        name: file

```

and command 121 Control Switches might look like this in JSON

```json
{
    "121": {
        "0": {
            "name": "switch_1_id",
            "type": "int"
        },
        "1": {
            "name": "switch_2_id",
            "type": "int"
        },
        "2": {
            "name": "switch_state",
            "type": "int"
        }
    }
}

```

as you can see YAML might be advantageous as it has the ability to place comments, YAML also can use JSON inline (JSON is actually a subset of YAML) which can be more readable that white space delineation in some cases

some information that may come in handy
https://gist.github.com/Ryex/1f12aecc6a5e6b115c24

This task will require actually opening a copy of rpgmaker xp and running some inspection on what different Event commands commands look like. I think the formater.py file list every command but there may be some that are unknown. if you need help figuring out what the event commands look like I'm sure we can come up with a script to drop into XP and (so long as you have an event on the map with every event command used in it) dump a representation out to a file.

This task will also require you to read the xp event interpreter script to decipher the meaning of each positional param. Just remember that there are some commands that are completely ignored by the interpreter as they are place holders

There are cases where the properties of a param change based on what came before it in which case the values should be under keys with conditional statements, the exact syntax of this should be a topic of discussion in this thread.

an example of this case is command 111 the Conditional Branch
param[0] is the command mode and bases on it's value subsequent params may refer to switches, variables, self switches etc. and some params might not even exist

in the case where a param is an int but maps to different operations or modes there should be a "map" key that maps the modes. for example if the param refers to what math operator to use the map should have a map key like so

```yaml
xxx:
    x:
        type: int
        name: operator
        map: { 0: '==', 1: '>=', 2: '<=', 3: '>', 4: '<', 5: '!='}
```

If there are any question or you would like to help out in making this map, please post below. [b]You don't have to contribute all of the map to be helpful![/b], even if you only contribute one command, or even one param for a command it's helpful

**Comment by Ryex** [comment]
So I've been trying to write up an example command trying to ensure that I have all the data I need to both format the event in the display and construct a property pane for it

I figured command 111 (Conditional Branch) would be a good example
It' not done but I THINK this example for the parts filled out so far has enough data

The idea is to describe what each param ends up being while describing a display mode
when property panels get constructed I envision adding a row for each param that is context sensitive to data in previous param boxes. disabling or perhaps replacing controls 

Here is a partial YAML map of command 111
```yaml
111:
    0:
        name: name
        type: int
        display: dropdown
        map: {
                0: 'Switch',  1: 'Variable', 2: 'Self Switch', 3: 'Timer',
                4: 'Actor', 5: 'Enemy', 6: 'character', 7: 'Gold', 8: 'Item',
                9: 'Weapon', 10: 'Armor', 11: 'Button', 12: 'Script'
            }
        limit: [0, 12]
        text: If
    cond:
        param: 0
        switch:
            0: # switch
                1:
                    name: switch
                    type: switch_id
                2:
                    name: switch_state
                    type: int
                    display: dropdown
                    map: {0: true, 1: false}
                    options: [0, 1]
                    text: is
            1: # variable
                1:
                    name: var_one
                    type: variable_id
                2:
                    name: variable_mode
                    type: int
                    display: radio
                    map: {0: Constant, 1: Variable}
                    text: Compare to
                3:
                    cond:
                        param: 2
                        if: ==
                        value: 0
                        then:
                            name: value
                            type: [num, str]
                            display: box
                        else:
                            name: var_two
                            type: variable_id
                    text: null
                4: 
                    name: operation
                    type: int
                    display: dropdown
                    map:{0: '==', 1: '>=', 2: '<=', 3: '>', 4: '<', 5: '!='}
                    hint: oper_logic
            2: # self switch
                1:
                    name: self_switch
                    type: str
                    display: box
                2:
                    name: value
                    type: int
                    map: {0: true, 1: false}
                    options: [0, 1]
            3: # timer
                1:
                    name: timer_seconds
                    type: int
                    display: spinner
                    hint: timer
                    limit: [0, null]
                2:
                    name: timer_mode
                    type: int
                    map: {0: ">=", 1: "<="}
                    hint: oper_logic
            4: # actor
                1:
                    name: actor
                    type: actor_id
                2:
                    name: actor_mode
                    type: int
                    display: dropdown
                    map: {
                        0: In Party
                        1: Name
                        2: Skill
                        3: Weapon
                        4: Armor
                        5: State
                    }
                    limit: [0, 5]
                3:
                    cond:
                        param: 2
                        switch:
                            1:
                                name: actor_name
                                type: str
                                text: Has
                            2:
                                name: skill
                                type: skill_id
                                text: Learned
                            3:
                                name: weapon
                                type: weapon_id
                                text: Equiped
                            4:
                                name: armor
                                type: armor_id
                                text: Equiped
                            5:
                                name: state
                                type: state_id
                                text: Inflicted

            5:
                1:
                    name: enemy
                    type: int
            6:
            7:
            8:
            9:
            10:
            11:
            12:
    3:
        cond:
            param: 0
            type: case
            when:
                0: #switch
                1: # variable
                    
                2:
                3:
                4:
                5:
                6:
                7:
                8:
                9:
                10:
                11:
                12:
    4:
        cond:
            param: 0
            type: case
            when:
                0: #switch
                1: # variable
                    name: operation
                    type: int
                    display: dropdown
                    map:{0: '==', 1: '>=', 2: '<=', 3: '>', 4: '<', 5: '!='}
                    hint: oper_logic
                2:
                3:
                4:
                5:
                6:
                7:
                8:
                9:
                10:
                11:
                12:
```

**Comment by tcrane20** [comment]
Since I did this at the start of my joining, I might as well be the one to do it. I just need a bit of explanation on the syntax and what extra things you require (like I see dropdown and oper_logic and I know for a fact that has nothing to do with RMXP's Interpreter).

**Comment by Ryex** [comment]
the point of properties like `display` and `hint` are to give the Editor a way to present a GUI for setting the param that makes sense.
I guess I'll write up an explanation

```yaml
xxx: # where xxx in the command number
    name: # name of the command
    x: # where x is a peram index
        cond:
        name:
        type:
            - switch_id
            - variable_id
            - item_id
            - weapon_id
            - armor_id
            - ect.
            - int
            - float
            - num # (int or float)
            - str
            - num_str # (entered as text but will atempt to parse a num, if faisl defaults to string)
            - color
            - tone
            - image
            - bgs
            - me
            - se
            # and more if appropriate
        map: # a mapping of stored values to display values
        # if of appropriate type clamps the value inclusively, if either top or bottom is null unclamps on that end
        # default is no clamping
        limit: [top, bottom] 
        display: # usd to help the editor for gui purposes
            - box
            - dropdown
            - spinner
            - radio
            - check
            # the default is box which is a basic editable entry box
            # some types inply a display, dropdown for example is implied by all *_id types, spinner by a clamped int or num
        # used to help interperate values
        # oper_logic for example would hint the editor to conver things like == and >= to `equal too` and `greater than or equal to`
        # timer would tell the editor to use a pair of spinners for minutes and seconds but store as the total seconds
        hint: 
        text: #a displayed label for the value
    cond: # condition all other properties at teh same level are processed first
        # can have any of the folowing sets
        #--------------
        if:
            #------
            param:
            value:
            # OR
            paramL:
            paramR:
            #------
            oper: # set to a string operator of the form == <= >= != < >
            # Optional
            # and has presadence over or, the full and branch will be processed apending conditions before the or branch
            and:
                # all possible values of if except then
            or:
                # all possible values of if except then including more and / or's
            then: # all the properties of branch must past
                x: # sets the properties of param index x
        elseifx: # elseifx are processed in order from elseif1 untill a consecutive elseifx can not be found
            # all possible values of if
        else: # fall through, then is implied
            x: #set properties of param index x
        #---------------
        switch: # property keys are values param can take
            param:
            y: # y is replaced with arbatrary or number or string that param can take
                cond:
                x: # sets the properties of param index x
        else:
            x: # set x if none of the switch cases are true
        #---------------
```
